---
- hosts: all
  vars:
    RUNNER_VERSION: 2.169.1
  vars_prompt:
    - name: "ORG"
      prompt: "What is the GitHub organization associated with this self-hosted runner?"
      private: no
    - name: "REPO"
      prompt: "What is the GitHub repository associated with this self-hosted runner?"
      private: no
    - name: "RUNNER_NAME"
      prompt: "Under what name should the runner show up on GitHub?"
      private: no
      default: GitHub Action Runner
    - name: "PERSONAL_ACCESS_TOKEN"
      prompt: "Please enter a personal access token for this workflow. Go to https://github.com/settings/tokens to get it."
      private: no

  tasks:
    - name: Verify that user exists on the server
      become: True
      user:
        name: "{{ ansible_user }}"
        groups: sudo,adm
        state: present

    - name: Showing the input variables
      debug:
        msg: "Setting up a GitHub runner for repository: https://github.com/{{ ORG }}/{{ REPO }}"

    - name: Only run "apt update-cache" if the last one is more than 3600 seconds old
      become: True
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install jq
      become: True
      apt:
        name:
          - jq
          - curl
        state: present

    - name: "Requesting registration"
      shell:
        cmd: "curl -sX POST -H \"Authorization: token {{ PERSONAL_ACCESS_TOKEN }}\" \"https://api.github.com/repos/{{ ORG }}/{{ REPO }}/actions/runners/registration-token\" | jq .token --raw-output"
      register: CURL_OUTPUT
      tags:
        - uninstall
      args:
        warn: false

    - name: Creating a directory for the runner
      file:
        path: /home/tester/opt/actions-runner/{{ ORG }}/{{ REPO }}
        state: directory

    - name: Downloading and extracting the runner
      unarchive:
        src: https://github.com/actions/runner/releases/download/v{{ RUNNER_VERSION }}/actions-runner-linux-x64-{{ RUNNER_VERSION }}.tar.gz
        dest: /home/tester/opt/actions-runner/{{ ORG }}/{{ REPO }}
        creates: /home/tester/opt/actions-runner/{{ ORG }}/{{ REPO }}/config.sh
        remote_src: yes

    - name: Configuring the GitHub Action runner
      shell:
        chdir: /home/tester/opt/actions-runner/{{ ORG }}/{{ REPO }}
        cmd: ./config.sh --url https://github.com/{{ ORG }}/{{ REPO }} --name {{ RUNNER_NAME }} --token {{ CURL_OUTPUT.stdout }} --unattended --replace

    - name: Install the GitHub Action runner as a service
      become: True
      shell:
        chdir: /home/tester/opt/actions-runner/{{ ORG }}/{{ REPO }}
        cmd: ./svc.sh install

    - name: Enable starting the runner service when the machine starts
      become: True
      shell: systemctl enable actions.runner.{{ ORG }}-{{ REPO }}.{{ RUNNER_NAME }}.service
      tags:
        - enable

    - name: Starting the runner service
      become: True
      shell: systemctl start actions.runner.{{ ORG }}-{{ REPO }}.{{ RUNNER_NAME }}.service
      tags:
        - start

    - name: Stopping the runner service
      become: True
      shell: systemctl stop actions.runner.{{ ORG }}-{{ REPO }}.{{ RUNNER_NAME }}.service
      tags:
        - never
        - stop

    - name: Disable starting the runner service when the system boots
      become: True
      shell: systemctl disable actions.runner.{{ ORG }}-{{ REPO }}.{{ RUNNER_NAME }}.service
      tags:
        - never
        - disable

    - name: Restart the runner service
      become: True
      shell: systemctl restart actions.runner.{{ ORG }}-{{ REPO }}.{{ RUNNER_NAME }}.service
      tags:
        - never
        - restart

    - name: Show the runner service status
      become: True
      shell: systemctl status actions.runner.{{ ORG }}-{{ REPO }}.{{ RUNNER_NAME }}.service
      tags:
        - never
        - status

    - name: Unregister the runner with GitHub
      become: True
      shell:
        chdir: /home/tester/opt/actions-runner/{{ ORG }}/{{ REPO }}
        cmd: ./svc.sh uninstall
      tags:
        - never
        - uninstall

    - name: Unregister the runner with GitHub and uninstall the runner service
      shell:
        chdir: /home/tester/opt/actions-runner/{{ ORG }}/{{ REPO }}
        cmd: ./config.sh remove --token {{ CURL_OUTPUT.stdout }}
      tags:
        - never
        - uninstall
