name: GitHub-hosted CI example

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Show directory listing
        shell: bash -l {0}
        run: |
          ls -la
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@v4.1.0
        with:
          targets: |
           ubuntu-vagrant/runner/playbook.yml
           ubuntu-surf-hpc-cloud/runner/playbook.yml
           ubuntu-virtualbox/runner/playbook.yml
           windows-vagrant/runner/playbook.yml
